version: '3.9'

services:
  backend:
    container_name: umaru
    build:
      context: . 
      dockerfile: Dockerfile
      args:
        GO_PORT: ${GO_PORT:-4000} 
        GO_ENV: "development" 
        CORS_TRUSTED_ORIGINS: ${CORS_TRUSTED_ORIGINS:-localhost:4000 localhost:5000 localhost:6000}
    ports:
      - ${GO_PORT:-4000}:${GO_PORT:-4000}
    environment:
      UMARU_DB_DSN: "postgres://postgres:dev1234@postgres/umaru?sslmode=disable"
    restart: unless-stopped
    depends_on: 
      - postgres
  postgres:
    container_name: postgres
    image: postgres:15.1
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=dev1234
     - POSTGRES_DB=umaru
    ports:
     - 5432:5432
    volumes: 
     - pgdata:/var/lib/postgresql/data:rw
    restart: unless-stopped
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@dev.com 
      PGADMIN_DEFAULT_PASSWORD: dev1234 
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
    - "8889:80"
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin 
    depends_on:
      - postgres
volumes:
 pgdata:
 pgadmin: